### ISSUE TITLE
Error loading GUI

### ISSUE THREAD

**Issue by teemu-ruokolainen** [AaltoPML/VAI-Lab#89]
__Problem__:

Error loading GUI when starting from command line without arguments.

`vai_lab`

__Error message__:

Loading GUI
To load existing config, run core.load_config_file(<path_to_file>)
Traceback (most recent call last):
  File "/u/92/ruokolt1/unix/micromamba/envs/vailab/bin/vai_lab", line 8, in <module>
    sys.exit(main())
  File "/u/92/ruokolt1/unix/micromamba/envs/vailab/lib/python3.10/site-packages/vai_lab/run_pipeline.py", line 62, in main
    core.run()
  File "/u/92/ruokolt1/unix/micromamba/envs/vailab/lib/python3.10/site-packages/vai_lab/Core/vai_lab_core.py", line 171, in run
    self._initialise_with_gui()
  File "/u/92/ruokolt1/unix/micromamba/envs/vailab/lib/python3.10/site-packages/vai_lab/Core/vai_lab_core.py", line 167, in _initialise_with_gui
    self._launch()
  File "/u/92/ruokolt1/unix/micromamba/envs/vailab/lib/python3.10/site-packages/vai_lab/Core/vai_lab_core.py", line 30, in _launch
    gui_output = gui_app.launch()
  File "/u/92/ruokolt1/unix/micromamba/envs/vailab/lib/python3.10/site-packages/vai_lab/GUI/GUI_core.py", line 146, in launch
    frame = F(parent=container, controller=self,
  File "/u/92/ruokolt1/unix/micromamba/envs/vailab/lib/python3.10/site-packages/vai_lab/utils/plugins/MainPage.py", line 35, in __init__
    self._setup_frame()
  File "/u/92/ruokolt1/unix/micromamba/envs/vailab/lib/python3.10/site-packages/vai_lab/utils/plugins/MainPage.py", line 58, in _setup_frame
    bg=parent['bg'])
NameError: name 'parent' is not defined. Did you mean: 'print'?

**Comment by cam586** [comment]
Fixed in #90  - will be merged soon

The problem was that parent was being referenced outside of init. Fixed by referencing `self.bg` class variable instead

**Comment by cam586** [comment]
Closed in #90
